### ISSUE TITLE
Recommended antennae and shield?

### ISSUE THREAD

**Issue by jknotten** [mouse256/evomon#1]
I'm looking to try out your evohome monitoring software, but being a newbie I'm not sure exactly what hardware to buy. The store on http://shop.busware.de/product_info.php/products_id/29 offers options for the antennae and shield. Do you have any recommendations here?

**Comment by mouse256** [comment]
Sure.
You'll need the 868Mhz version. I just have the "wire" antenna, but you'll probably have better coverage with the other ones.
I don't believe I have the HF shield.

But I would also suggest to take a look at this thread (especially in the end) http://www.domoticaforum.eu/viewtopic.php?f=7&t=5806
There are some guys who managed with different hardware also to control the evotouch. With my setup you can't control it.

**Comment by jknotten** [comment]
Brilliant, thanks very much for the information.
